name: adapter-sqlite

on:
  workflow_dispatch:
    inputs:
      skip_commit:
        description: "Skip commit results"
        required: false
        type: boolean
        default: false

jobs:
  run-benchmark:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ver: "bun"
            os: "ubuntu-latest"
            adapter: "sqlite"
            install: ""
          - ver: "24"
            os: "ubuntu-latest"
            adapter: "sqlite"
            install: ""
          - ver: "22"
            os: "ubuntu-latest"
            adapter: "sqlite"
            install: ""
          - ver: "24"
            os: "windows-latest"
            adapter: "sqlite"
            install: ""
          - ver: "bun"
            os: "windows-latest"
            adapter: "sqlite"
            install: ""
          - ver: "24"
            os: "macos-latest"
            adapter: "sqlite"
            install: ""
          - ver: "bun"
            os: "macos-latest"
            adapter: "sqlite"
            install: ""
          - ver: "24"
            os: "ubuntu-latest"
            adapter: "sqlite:better"
            install: "better-sqlite3"
          - ver: "22"
            os: "ubuntu-latest"
            adapter: "sqlite:better"
            install: "better-sqlite3"
          - ver: "24"
            os: "windows-latest"
            adapter: "sqlite:better"
            install: "better-sqlite3"
          - ver: "24"
            os: "macos-latest"
            adapter: "sqlite:better"
            install: "better-sqlite3"

    uses: ./.github/workflows/run-single.yml
    with:
      opts: '["./valthera-sqlite-test-$$.sqlite", {}, {}]'
      adapter: ${{ matrix.adapter }}
      ver: ${{ matrix.ver }}
      os: ${{ matrix.os }}
      install: ${{ matrix.install }}
      setup: ""
    secrets: inherit

  commit-results:
    needs: run-benchmark
    if: ${{ github.event.inputs.skip_commit != 'true' }}
    uses: ./.github/workflows/commit-results.yml
    with:
      adapter: "sqlite"
    secrets: inherit
