name: adapter-dir-c

on:
  workflow_dispatch:

jobs:
  run-benchmark:
    strategy:
      matrix:
        include:
          - ver: "bun"
            os: "ubuntu-latest"

    uses: ./.github/workflows/run-single.yml
    with:
      opts: '["./valthera-dir-c-test"]'
      adapter: "dir-c"
      ver: ${{ matrix.ver }}
      os: ${{ matrix.os }}
      install: ""
      setup: |
        sudo apt update
        sudo apt install -y cmake make
        mkdir -p node_modules/@wxn0brp
        cd node_modules/@wxn0brp
        git clone https://github.com/wxn0brP/ValtheraDB-c-engine.git db-dir-c
        cd db-dir-c
        mkdir -p build && cd build
        cmake ..
        make build
    secrets: inherit

  commit-results:
    needs: run-benchmark
    uses: ./.github/workflows/commit-results.yml
    with:
      adapter: "dir-c"
    secrets: inherit
