name: adapter-dir-c

on:
  workflow_dispatch:
    inputs:
      skip_commit:
        description: "Skip commit results"
        required: false
        type: boolean
        default: false

jobs:
  run-benchmark:
    strategy:
      max-parallel: 4
      matrix:
        include:
          - ver: "bun"
            os: "ubuntu-latest"

    uses: ./.github/workflows/run-single.yml
    with:
      opts: '["./valthera-dir-c-test-$$"]'
      adapter: "dir-c"
      ver: ${{ matrix.ver }}
      os: ${{ matrix.os }}
      install: "@wxn0brp/db-storage-dir"
      setup: |
        sudo apt update
        sudo apt install -y cmake make pkg-config libjansson-dev
        mkdir -p node_modules/@wxn0brp
        cd node_modules/@wxn0brp
        git clone https://github.com/wxn0brP/ValtheraDB-c-engine.git db-storage-dir-c
        cd db-storage-dir-c
        mkdir -p build && cd build
        cmake ..
        make
    secrets: inherit

  commit-results:
    needs: run-benchmark
    if: ${{ github.event.inputs.skip_commit != 'true' }}
    uses: ./.github/workflows/commit-results.yml
    with:
      adapter: "dir-c"
      one: "dir-c__bun__ubuntu-latest"
    secrets: inherit
