name: adapter-mongodb

on:
  workflow_dispatch:
    inputs:
      skip_commit:
        description: "Skip commit results"
        required: false
        type: boolean
        default: false

jobs:
  run-benchmark:
    strategy:
      matrix:
        include:
          - ver: "bun"
            os: "ubuntu-latest"
          - ver: "24"
            os: "ubuntu-latest"
          - ver: "22"
            os: "ubuntu-latest"
          - ver: "20"
            os: "ubuntu-latest"

    uses: ./.github/workflows/run-single.yml
    with:
      opts: '["mongodb://127.0.0.1:27017", "valthera-mongodb-test-$$", true]'
      adapter: "mongodb"
      ver: ${{ matrix.ver }}
      os: ${{ matrix.os }}
      install: "@wxn0brp/db-storage-mongodb"
      setup: |
        docker run -d --name valthera-mongodb -p 27017:27017 mongo:8
        for i in {1..30}; do
          if docker exec valthera-mongodb mongosh --quiet --eval "db.adminCommand('ping').ok" | grep -q 1; then
            exit 0
          fi
          sleep 2
        done
        docker logs valthera-mongodb
        exit 1
    secrets: inherit

  commit-results:
    needs: run-benchmark
    if: ${{ github.event.inputs.skip_commit != 'true' }}
    uses: ./.github/workflows/commit-results.yml
    with:
      adapter: "mongodb"
    secrets: inherit
