name: clean-branch

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string

jobs:
  clean-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Clean and recreate branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin --delete ${{ inputs.branch }} || true
          git checkout --orphan ${{ inputs.branch }}
          git reset --hard
          git commit --allow-empty -m "Initialize ${{ inputs.branch }} branch"
          git push origin ${{ inputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
