name: commit-results

on:
  workflow_call:
    inputs:
      adapter:
        required: true
        type: string

jobs:
  commit-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results branch
        uses: actions/checkout@v6
        with:
          ref: results

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: .

      - run: ls -al

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/wxn0brP/ValtheraDB-benchmark.git
          git add .
          git commit -m "Results ${{ inputs.adapter }}"
          git push origin results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
