name: commit-results

on:
  workflow_call:
    inputs:
      adapter:
        required: true
        type: string
      one:
        required: false
        type: string

jobs:
  commit-results:
    runs-on: ubuntu-latest
    concurrency:
      group: results-branch-push
      cancel-in-progress: false
    steps:
      - name: Checkout results branch
        uses: actions/checkout@v6
        with:
          ref: results

      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: .
          merge-multiple: false

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          ls -al
          if [ -f results.json ]; then
            mkdir -p ${{ inputs.one }}
            mv results.json ${{ inputs.one }}/result.json
          fi
          
          git add .
          git commit -m "Results ${{ inputs.adapter }}"
          git push origin results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
