name: run-single

on:
  workflow_call:
    inputs:
      opts:
        required: true
        type: string
      adapter:
        required: true
        type: string
      ver:
        required: true
        type: string
      os:
        required: true
        type: string
      install:
        required: false
        type: string
      setup:
        required: false
        type: string

jobs:
  benchmark-single:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: bash

    env:
      IS_BUN: ${{ inputs.ver == 'bun' }}
      RUNTIME: ${{ inputs.ver == 'bun' && 'bun' || 'node' }}
      INSTALL_CMD: ${{ inputs.ver == 'bun' && 'bun install' || 'npm install' }}
      ADD_CMD: ${{ inputs.ver == 'bun' && 'bun add' || 'npm install' }}
      BUILD_CMD: ${{ inputs.ver == 'bun' && 'bun run build' || 'npm run build' }}
      EXEC_CMD: ${{ inputs.ver == 'bun' && 'bun run dist/index.js' || 'node dist/index.js' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        if: env.IS_BUN == 'true'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js
        if: env.IS_BUN != 'true'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.ver }}

      - name: Install dependencies
        run: $INSTALL_CMD

      - name: Install additional dependencies
        if: inputs.install
        run: $ADD_CMD ${{ inputs.install }}

      - name: Custom setup
        if: inputs.setup
        run: ${{ inputs.setup }}

      - name: Build
        run: $BUILD_CMD

      - name: Run benchmark 3 times
        env:
          VALTHERA_MASTER: ${{ inputs.adapter }}
          VALTHERA_MASTER_OPTS: ${{ inputs.opts }}
        run: |
          for i in {1..3}; do
            echo "-------------> Benchmark run $i"
            $EXEC_CMD
          done

      - name: Prepare artifact name
        run: |
          ARTIFACT_NAME="${{ inputs.adapter }}__${{ inputs.ver }}__${{ inputs.os }}"
          ARTIFACT_NAME=$(echo "$ARTIFACT_NAME" | tr ':' '-')
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: result.json
