name: run-all

on:
  workflow_dispatch:
    inputs:
      skip_commit:
        description: "Skip commit results"
        required: false
        type: boolean
        default: false

jobs:
  adapter-bin:
    uses: ./.github/workflows/adapter-bin.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-dir:
    needs: adapter-bin
    if: always()
    uses: ./.github/workflows/adapter-dir.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-dir-c:
    needs: adapter-dir
    if: always()
    uses: ./.github/workflows/adapter-dir-c.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-dir-index:
    needs: adapter-dir-c
    if: always()
    uses: ./.github/workflows/adapter-dir-index.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-memory:
    needs: adapter-dir-index
    if: always()
    uses: ./.github/workflows/adapter-memory.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-mongodb:
    needs: adapter-memory
    if: always()
    uses: ./.github/workflows/adapter-mongodb.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}

  adapter-sqlite:
    needs: adapter-mongodb
    if: always()
    uses: ./.github/workflows/adapter-sqlite.yml
    with:
      skip_commit: ${{ inputs.skip_commit }}
